# Generated by Django 5.1.1 on 2024-09-06 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('cpu_cooler', models.CharField(max_length=100)),
                ('motherboard', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
