# Generated by Django 5.1.1 on 2024-09-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
